FROM node:7.5.0-alpine

RUN apk add --update \
    findutils \
    g++ \
    make \
    postgresql \
    postgresql-dev \
    python

ADD server/package.json tmp/package.json
RUN cd tmp && npm install
RUN mkdir server && mv tmp/node_modules server/node_modules

ADD server server
ENV SKIP_AWS=1
CMD cd server && sh test.sh

EXPOSE 80 443
